### ISSUE TITLE
Issues with 1.19.3

### ISSUE THREAD

**Issue by mustafakamran98** [TeamMidnightDust/MidnightControls#141]
**Describe the bug**
The game will crash upon starting in 1.19.3 with PrismLauncher 5.2, Fabric Loader 0.14.11, and Fabric API 0.68.1+1.19.3

**To Reproduce**
1. Launch with only Fabric API and MidnightControls selected as mods

**Expected behavior**
Game should launch with no problem

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.19.3
 - Fabric Loader 0.14.11
 - Fabric API 0.68.1+1.19.3
 - Version 1.7.1+1.19.1

**Logs:** https://mclo.gs/lQipzAh

**Comment by mustafakamran98** [comment]
Using the 22w43a snapshot version of the mod on 1.19.3 does not work either. Logs with Mod Menu and Fabric API enabled: https://mclo.gs/Q3pfdih

**Comment by Motschen** [comment]
Fixed in 1.7.2
Have fun :)

**Comment by SCAbruh** [comment]
I'm still having this issue on the steamdeck. Only other mods are FabricAPI and Sodium. Log attached.
[crash-2023-01-02_15.14.27-client.txt](https://github.com/TeamMidnightDust/MidnightControls/files/10333373/crash-2023-01-02_15.14.27-client.txt)

**Comment by PRGilland** [comment]
I also have this same exact issue on Steam Deck, with or without mods, using Prism Launcher.

**Comment by mustafakamran98** [comment]
I seem to be experiencing the same issue after updating Fabric API to 0.71.0+1.19.3. I might consider filing a separate issue to open it again.

**Comment by mustafakamran98** [comment]
Please refer to #154 before commenting further on this issue.
